# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Calle')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='N\xfamero')),
                ('slug', models.SlugField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Commune', verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Direcci\xf3n',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Regi\xf3n',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.State', verbose_name='Regi\xf3n'),
        ),
    ]
