# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.Commune', verbose_name='Comuna'),
        ),
    ]
