# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20160320_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='direction',
            name='lng',
            field=models.FloatField(default=0, verbose_name='longitud'),
        ),
    ]
