# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('slug', models.SlugField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Direction', verbose_name='Direcci\xf3n')),
            ],
            options={
                'ordering': ['-order'],
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
