# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Sucursal activa'),
        ),
    ]
